### ISSUE TITLE
Start() not available in .Core version

### ISSUE THREAD

**Issue by large** [darksody/KrakenIPC#1]
Hi! KrakenIPC seems like a tool I am looking for, simple IPC with not much hazzle.

I have a .net 472 as a server and asp core 3.1 as a client, installed Kraken.Core on both of them.
But I don't see the Start() function because the class is presented as this
```
namespace KrakenIPC
{
    public class PipeServer<T, U> where T : class, new()
    {
        public PipeServer();

        public event Action<Exception> OnPipeException;
        public event Action<bool> OnPipeConnectionChanged;
    }
}
```

In the none .core version class is installed on the .net 472, it is like this.

```
namespace KrakenIPC
{
    public class PipeServer<T, U> where T : class, new()
    {
        public PipeServer();

        public event Action<Exception> OnPipeException;
        public event Action<bool> OnPipeConnectionChanged;

        public void SetDefaultSecurity();
        public void SetSecurity(PipeSecurity pipeSecurity);
        public void Start();
        public void Stop();
    }
}
```
I always gets the client-timeout as for now from the client, so it is non functional for me atm.
Probably something with the missing functions?

**Comment by darksody** [comment]
Hello,

I have just updated the .Core nuget package. I did some refactoring and forgot to update the core package as well.
The reason i keep them separate is because of the pipe security -> it's not available on .net Core. I mean it is, but only for Windows, doesn't work on MacOS X or Linux.

Regarding the client timeouts, it's configured for 3 seconds by default. If you need a bigger time (or if you spend that time in debugging mode), then it will throw a timeout exception.
You can configure the timeout on the constructor of the PipeClient for as much as you like (it's in milliseconds).
Let me know if you have other issues.

**Comment by large** [comment]
It still didn't work, since the baseclasses are different.

I used your example and created an Client.Core to test.
There is an Exception within JsonConvert and they are not catched, so you get "timeout" in the client since the server reply.

If you look at the string every core request is linked to System.Private.Corelib and every .Net 472 is linked to mscorlib. Since the server isn't .Core it will create an assert.

**Comment by darksody** [comment]
Hello @large ,

I now understand what you mean.
Indeed, having a .net framework server and a .net core client (or viceversa) doesn't work, exactly because of the System.Private.Corelib library.

I'm working on a solution for it, will let you know once i manage something.

**Comment by large** [comment]
Great, it failed on Deserialize: https://github.com/darksody/KrakenIPC/blob/4d32b7a590f1974c6da15ec4638e7105c66b0b19/KrakenIPC/KrakenIPC/Models/PipeMessage.cs#L12-L15

Here was the results:
.Core:
> {"MethodName":"GetData","ParameterTypes":["System.Int32, **System.Private.CoreLib**, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"],"ParameterValues":[3],"ReturnType":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"}

.Net:
> {"MethodName":"GetData","ParameterTypes":["System.Int32, **mscorlib**, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"],"ParameterValues":[3],"ReturnType":"System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"}

**Comment by darksody** [comment]
Managed to build a custom serializer to omit the assembly name. However, this needs to be omitted only for system types (mscorlib or system.private.corelib, and maybe there are others as well). This is because if i omit it for every type, the deserialization won't work (since i need an assembly name to deserialize a type).

Long story short:
Right now, you need to use the client and the server on the same framework (either .net 4.5+ or .net core).
It will take some time until i figure out how to serialize "Type" objects and deserialize them without having to specify the assembly name. The only solution i have right now is to purposely omit the mscorlib and System.Private.Corelib assemblies, but it might add a performance impact.

**Comment by large** [comment]
Thank you for the feedback @darksody 
I use https://github.com/jacqueskang/IpcServiceFramework now and int as a parameter works on that framework. Maybe there are some tips there...

Also found this example that might could solve some of it: https://gist.github.com/john-cullen/c39d56efcb15e60b66cd4d05149316ed
(A underlink of https://stackoverflow.com/questions/50190568/net-standard-4-7-1-could-not-load-system-private-corelib-during-serialization )

I can't believe that some of the clever heads out there haven't figured that out yet :)

**Comment by darksody** [comment]
Hello,

The JKang's IpcServiceFramework has the same issue if you get a .net core client with a .net framework server. 

The other 2 links you have shared, are quite useful. I can see they have the same approach of not including the assembly name for System.Private.CoreLib.
I can do the same, maybe even use that regex of theirs. However, i'm afraid of the performance impact. I'll include a flag to both server and client for "CrossFrameworkCompatibility", so if you don't need it, you just won't use it.

**Comment by large** [comment]
That is a great implementation that would work.
In my application the IPC rate is not critical. The .core is used as a gui for the .net service and force reloads of config etc... That is like one trigger pr save ;)
I'll be gone for 4 weeks and I'll try your IPC framework when I am back.

**Comment by large** [comment]
I had a good go on the gRPC and it was totally overkill.
Started to look into the pipes again and combined your project with a Full Duplex Pipes.
The result was this project: https://github.com/large/SimpleCrossPIPE
